### ISSUE TITLE
HEOM did not work with categorical columns.

### ISSUE THREAD

**Issue by maisonhai3** [KacperKubara/heterogeneous_dist_metrics#11]
I took a look at your code to find out why it didn't work with my data. Here my found.

At HEOM.py.
```
# Get the normalization scheme for numerical variables
if normalised == "std":
self.range = 4* np.nanstd(X, axis = 0)
else:
self.range = np.nanmax(X, axis = 0) - np.nanmin(X, axis = 0)
```

You lay a cat_ix to identify categorical variables, but it did not be used while setting range for HEOM.

X should have split apart numericals and categoricals with cat_ix, but it did not. So if the input dataset includes categorical columns, np.nanmax would raise an error as it can not handle categories.

**Comment by KacperKubara** [comment]
Hi, thanks for the opening an issue.

I see your point, good finding. The reason why I've done is that it was slightly easier to access the range for each numerical variable if I don't change the shape of the vector. So it is effectively still possible use the same numerical indices passed to the class as the `self.range` has the same shape as `x` and `y` vector. This allows to just make a code slightly clearer and get a range for each numerical variable with one line of code: ` results_array[num_ix] = np.abs(x[num_ix] - y[num_ix]) / self.range[num_ix]`.

To use this metric, you need to convert categorical variables to integer labels first. You can do it with Sklearn labelencoder. Have you done that already? Or is there any other error that you've encountered?

**Comment by maisonhai3** [comment]
Oh, I understood your idea.

LabelEncoder works well. Thank you. :D
