### ISSUE TITLE
variance option has standard deviation in the paper

### ISSUE THREAD

**Issue by smferro54** [KacperKubara/heterogeneous_dist_metrics#4]
This line:
            self.range = 4* np.nanvar(X, axis = 0)
Uses the standard deviation in the paper in order to get all datapoints inside a 95% interval (assuming a normal distribution).

**Comment by KacperKubara** [comment]
The function
 `np.nanvar(X, axis=0)`
has to be replaced with
`np.nanstd(X, axis=0)`

I have replaced the function with the latest git push and it should be working now. The PyPI is not updated yet, but it will happen soon.
