### ISSUE TITLE
Error unsupported lists 

### ISSUE THREAD

**Issue by mronda** [KacperKubara/heterogeneous_dist_metrics#8]
Hi, 
I am trying to use distython to solve a problem that contains mixed types. I am using the df below as an example to establish my understanding of your package. 

0 | 1 | 2 | 3
-- | -- | -- | --
[Truck] | [Coffee] | -4.5 | 0.5
[EV] | [Juice] | 3.0 | 1.5
[Sedan] | [Beer] | -4.9 | 0.2

I am setting up the code like this:

```
cat_idx = [0,1]
heom_metric = HEOM(X, cat_idx)
```
And get this error: 

```unsupported operand type(s) for -: 'list' and 'list'```

What can I do in order to solve for this and be able to compare each row to obtain some distance ?

Thanks in advance !

**Comment by KacperKubara** [comment]
Hi @mronda,
I believe this related to this issue: https://github.com/KacperKubara/distython/issues/5
You will need to convert the categorical variables to numeric representation, .e.g [Truck] to 0, [EV] to 1, and [Sedan] to 2.
For the conversion, you can use the Scikit-learn LabelEncoder.
